export const social = {
  github: "https://github.com/NoxxyTheMain",
  linkedin: "https://www.linkedin.com/in/senteu-is-allan/",
  email: "senteualan@gmail.com",
  phone: "+254792226658"
};

export const projects = [
  { title: "AeroCruz", kind: "Ride-hailing platform", mark: "AC", visual: "MOVE WITH INTENT", description: "A practical ride-hailing platform concept shaped around the moving parts that make a digital service feel useful: riders, drivers, trips and clear interfaces.", problem: "How might everyday transport feel simpler to request and manage?", contribution: "Product thinking, interface design and the shape of a service’s data model.", stack: ["Web app", "UI / UX", "Database architecture"], github: "#" },
  { title: "Barclays Sunset Camp", kind: "Tourism & hospitality", mark: "BSC", visual: "THE STAY BEGINS HERE", description: "A considered web presence for a hospitality business—designed to present a destination with clarity, warmth and a path toward booking.", problem: "How can a digital visit create confidence before a guest arrives?", contribution: "Responsive design, user experience and a business-focused web presentation.", stack: ["Responsive design", "UX", "Booking flow"], github: "#" },
  { title: "Elite Wear & Ink", kind: "Web development", mark: "EWI", visual: "MADE TO BE WORN", description: "A frontend project focused on the fundamentals that matter: strong hierarchy, responsive behavior and a clear presentation of a brand’s offering.", problem: "How can a small brand make its work easy to discover online?", contribution: "Frontend implementation and responsive page design.", stack: ["HTML", "CSS", "JavaScript"], github: "#" },
  { title: "Security work in progress", kind: "Future projects", mark: "+", visual: "LAB NOTES / 001", description: "A home reserved for the experiments still ahead: security labs, network projects, Python tools and more deliberate work on authentication and web security.", problem: "The next layer of technical understanding.", contribution: "Learning in public—without pretending the work is finished.", stack: ["Linux", "Networking", "Web security"], github: "#" }
];

export const articles = [
  { slug: "new-study-partner", type: "Feature", category: "Technology & education", title: "The New Study Partner: How AI Is Changing University Learning in Kenya", excerpt: "A feature on how students and lecturers are weighing AI’s useful explanations against the risk of letting the tool do the thinking.", body: ["Generative AI is now a familiar presence in university learning. It can explain difficult concepts, summarise papers, help organise ideas and assist with debugging—but its arrival has made the question of learning more complicated.", "In this feature, I look at the tension through the experiences of university students: when AI helps someone move past a difficult technical problem, and when it turns into a shortcut that weakens understanding. The useful distinction is not whether a student uses AI, but whether they can explain and own the work that results.", "Technology has not replaced the classroom. It has added another voice to it. The challenge for universities is to make that voice support curiosity, critical thinking and academic integrity rather than substitute for them."] },
  { slug: "maasai-rites-of-passage", type: "Feature", category: "Culture & technology", title: "The Maasai Rites of Passage Are Changing. So Is How They Are Remembered", excerpt: "How a generation carrying smartphones, university schedules and traditional obligations experiences Enkipaata, Eunoto and Olng’esherr differently.", body: ["Maasai rites of passage are not simply ceremonies that mark age. They are a process through which generations take on responsibility, cultural knowledge and a shared identity.", "This feature considers what happens when that process meets a generation living across university campuses, workplaces, homesteads and group chats. Smartphones and mobile money now help age-mates organise before they meet, while cameras change how ceremonies are remembered after they happen.", "The story is not about tradition being replaced by technology. It is about people making room for both: preserving the meaning of the rites while navigating a life that is more connected, mobile and digitally documented than before."] },
  { slug: "rethinking-education", type: "Essay", category: "Education", title: "Rethinking Education in the Digital Age", excerpt: "Why modern learning must go beyond memorisation to develop critical thinking, creativity, practical skills and digital literacy.", body: ["Education should do more than prepare students to reproduce information in an examination. It should develop the ability to analyse, evaluate, create and apply knowledge beyond the classroom.", "This essay argues for learning that connects concepts with real situations, gives students more responsibility for their progress and values reflection alongside assessment. A grade is not the whole picture of learning.", "In a digital environment, literacy also includes the ability to find information, judge its reliability, use it responsibly and communicate ideas clearly. Those skills matter as much as access to information itself."] },
  { slug: "special-needs-assessment", type: "Academic paper", category: "Education", title: "Approaches and Modifications for Students with Special Needs", excerpt: "An academic discussion of more inclusive assessment practices, including technology-supported alternatives to traditional testing.", body: ["Assessment should reveal what a learner understands, not merely what they can reproduce under one fixed set of conditions. For students with special needs, traditional tests do not always provide a complete or fair picture.", "This paper explores practical accommodations and alternative assessment approaches, including portfolios, observation, project work and technology-supported methods. The aim is to make room for different ways of demonstrating learning.", "Effective assessment depends on intentional collaboration among educators, students and families—and on designing conditions that allow learners to show their potential accurately."] },
  { slug: "monsters-university-reflection", type: "Academic reflection", category: "Culture", title: "Reflection on Monsters University", excerpt: "A reflection on stereotypes, social expectations, competition and the different ways people define success.", body: ["Monsters University uses a familiar story of ambition and competition to raise questions about social expectations. Its characters are judged by appearance, talent and their fit within institutional hierarchies.", "This reflection considers how the film contrasts inherited advantages with persistence, teamwork and the search for a meaningful definition of success. The story suggests that potential is not always visible at first glance.", "It also asks whether achievement has to follow one conventional path, or whether people can find value by recognising and developing their own strengths."] },
  { slug: "crime-prevention-strategy", type: "Academic paper", category: "Public policy", title: "Comprehensive Crime Prevention Strategy for Richardson", excerpt: "A proposal that combines immediate safety measures with long-term community investment and evidence-based prevention.", body: ["Crime prevention needs both immediate responses and a serious commitment to the conditions that shape safety over time. This paper proposes a socio-ecological approach that addresses people, communities and the built environment.", "Short-term priorities include community policing, attention to high-risk areas, lighting and care for neglected spaces. Long-term work focuses on education, mentorship, skills development and economic opportunity for young people.", "The central argument is that safety cannot be delivered by a single institution. It depends on meaningful coordination among residents, schools, businesses, public services and community organisations."] },
  { slug: "logistics-management", type: "Academic paper", category: "Business", title: "The Role of Logistics Management in Supply Chain Management", excerpt: "An overview of how movement, storage, inventory and information flow shape an efficient supply chain.", body: ["Logistics management sits at the centre of how goods, services and information move through a supply chain. It brings together transportation, warehousing, inventory, order processing and distribution.", "This paper discusses how thoughtful logistics planning can reduce operating costs, improve delivery reliability and help organisations respond to changing demand or disruption.", "The broader point is that logistics is not only operational detail. It is a strategic capability that supports customer experience, resilience and competitiveness."] }
];

export const skills = [
  { name: "Development", items: ["HTML", "CSS", "JavaScript", "React", "Next.js", "TypeScript"] },
  { name: "Backend & data", items: ["MySQL", "SQL", "APIs", "Database design"] },
  { name: "Tools", items: ["Git", "GitHub", "VS Code", "Vercel"] },
  { name: "Emerging focus", items: ["Cybersecurity", "Networking", "Linux", "Web security"] }
];
